-- SQL Script Generated by Tahlil Platform
-- Generated: 2025-12-26 22:01:36
-- Dialect: POSTGRESQL
-- Rows: 5
-- Columns: 7
--

-- Create Database
CREATE DATABASE test_db;

\c test_db


-- Create Table
CREATE TABLE IF NOT EXISTS employees (
    id BIGINT PRIMARY KEY NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    age BIGINT NOT NULL,
    salary DOUBLE PRECISION NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_employees_email ON employees (email);


-- Insert Data (5 rows)
INSERT INTO employees (id, name, email, age, salary, is_active, created_at) VALUES
    (1, 'John Doe', 'john@example.com', 28, 75000.5, True, '2024-01-15 00:00:00'),
    (2, 'Jane Smith', 'jane@example.com', 34, 85000.0, True, '2024-02-20 00:00:00'),
    (3, 'Bob O''Connor', 'bob@example.com', 45, 95000.75, False, '2024-03-10 00:00:00');

INSERT INTO employees (id, name, email, age, salary, is_active, created_at) VALUES
    (4, 'Alice Johnson', 'alice@example.com', 29, 72000.0, True, '2024-04-05 00:00:00'),
    (5, 'Charlie Brown', 'charlie@example.com', 52, 105000.25, True, '2024-05-12 00:00:00');



-- Script generation complete
-- Total INSERT statements: 2