-- SQL Script Generated by Tahlil Platform
-- Generated: 2025-12-26 22:01:36
-- Dialect: SQLITE
-- Rows: 5
-- Columns: 7
--

-- Create Database
-- SQLite database will be created when saving to file: test_db.db


-- Create Table
CREATE TABLE IF NOT EXISTS employees (
    id INTEGER NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    age INTEGER NOT NULL,
    salary REAL NOT NULL,
    is_active INTEGER NOT NULL,
    created_at TEXT NOT NULL
);


-- Insert Data (5 rows)
INSERT INTO employees (id, name, email, age, salary, is_active, created_at) VALUES
    (1, 'John Doe', 'john@example.com', 28, 75000.5, True, '2024-01-15 00:00:00'),
    (2, 'Jane Smith', 'jane@example.com', 34, 85000.0, True, '2024-02-20 00:00:00'),
    (3, 'Bob O''Connor', 'bob@example.com', 45, 95000.75, False, '2024-03-10 00:00:00'),
    (4, 'Alice Johnson', 'alice@example.com', 29, 72000.0, True, '2024-04-05 00:00:00'),
    (5, 'Charlie Brown', 'charlie@example.com', 52, 105000.25, True, '2024-05-12 00:00:00');



-- Script generation complete
-- Total INSERT statements: 1