-- SQL Script Generated by Tahlil Platform
-- Generated: 2025-12-26 22:11:16
-- Dialect: POSTGRESQL
-- Rows: 5
-- Columns: 10
-- Advanced Features: ENABLED
--

-- Create Database
CREATE DATABASE test_db;

\c test_db


-- Create Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY NOT NULL,
    customer_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    email VARCHAR(50) NOT NULL,
    full_name VARCHAR(50) NOT NULL,
    age BIGINT NOT NULL,
    salary DOUBLE PRECISION NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    is_verified BOOLEAN NOT NULL
);



-- CHECK Constraints (auto-detected)
ALTER TABLE users ADD CONSTRAINT chk_users_id_0 CHECK (id >= 0);
-- Reason: All values in 'id' are non-negative (min: 1)
ALTER TABLE users ADD CONSTRAINT chk_users_id_1 CHECK (id IN (1, 2, 3, 4, 5));
-- Reason: Column 'id' has only 5 unique values
ALTER TABLE users ADD CONSTRAINT chk_users_customer_id_2 CHECK (customer_id >= 0);
-- Reason: All values in 'customer_id' are non-negative (min: 101)
ALTER TABLE users ADD CONSTRAINT chk_users_customer_id_3 CHECK (customer_id IN (101, 102, 103));
-- Reason: Column 'customer_id' has only 3 unique values
ALTER TABLE users ADD CONSTRAINT chk_users_order_id_4 CHECK (order_id >= 0);
-- Reason: All values in 'order_id' are non-negative (min: 1001)
ALTER TABLE users ADD CONSTRAINT chk_users_order_id_5 CHECK (order_id IN (1001, 1002, 1003, 1004, 1005));
-- Reason: Column 'order_id' has only 5 unique values
ALTER TABLE users ADD CONSTRAINT chk_users_email_6 CHECK (email LIKE '%@%.%');
-- Reason: Column 'email' contains email addresses (100% valid)
ALTER TABLE users ADD CONSTRAINT chk_users_email_7 CHECK (email IN ('john@example.com', 'jane@example.com', 'bob@example.com', 'alice@example.com', 'charlie@example.com'));
-- Reason: Column 'email' has only 5 unique values
ALTER TABLE users ADD CONSTRAINT chk_users_full_name_8 CHECK (full_name IN ('John Doe', 'Jane Smith', 'Bob O'Connor', 'Alice Johnson', 'Charlie Brown'));
-- Reason: Column 'full_name' has only 5 unique values
ALTER TABLE users ADD CONSTRAINT chk_users_age_9 CHECK (age >= 0);
-- Reason: All values in 'age' are non-negative (min: 28)
ALTER TABLE users ADD CONSTRAINT chk_users_age_10 CHECK (age >= 0 AND age <= 150);
-- Reason: Column 'age' appears to be age (valid range: 0-150)
ALTER TABLE users ADD CONSTRAINT chk_users_age_11 CHECK (age IN (28, 34, 45, 29, 52));
-- Reason: Column 'age' has only 5 unique values
ALTER TABLE users ADD CONSTRAINT chk_users_salary_12 CHECK (salary >= 0);
-- Reason: All values in 'salary' are non-negative (min: 72000.0)
ALTER TABLE users ADD CONSTRAINT chk_users_salary_13 CHECK (salary IN (75000, 85000, 95000, 72000, 105000));
-- Reason: Column 'salary' has only 5 unique values
ALTER TABLE users ADD CONSTRAINT chk_users_status_14 CHECK (status IN ('active', 'inactive', 'pending'));
-- Reason: Column 'status' has only 3 unique values
ALTER TABLE users ADD CONSTRAINT chk_users_is_verified_15 CHECK (is_verified >= 0);
-- Reason: All values in 'is_verified' are non-negative (min: False)
ALTER TABLE users ADD CONSTRAINT chk_users_is_verified_16 CHECK (is_verified IN (1, 0));
-- Reason: Column 'is_verified' has only 2 unique values


-- Suggested Indexes (auto-detected)
CREATE UNIQUE INDEX idx_users_id ON users (id);
-- Priority: HIGH | 100% unique values with no nulls - candidate for UNIQUE constraint
CREATE INDEX idx_users_customer_id ON users (customer_id);
-- Priority: HIGH | Foreign key column - frequently used in JOINs
CREATE UNIQUE INDEX idx_users_order_id ON users (order_id);
-- Priority: HIGH | 100% unique values with no nulls - candidate for UNIQUE constraint
CREATE INDEX idx_users_order_id ON users (order_id);
-- Priority: HIGH | Foreign key column - frequently used in JOINs
CREATE UNIQUE INDEX idx_users_email ON users (email);
-- Priority: HIGH | 100% unique values with no nulls - candidate for UNIQUE constraint
CREATE INDEX idx_users_email ON users (email);
-- Priority: HIGH | Email column - commonly used for user lookup
CREATE UNIQUE INDEX idx_users_full_name ON users (full_name);
-- Priority: HIGH | 100% unique values with no nulls - candidate for UNIQUE constraint
CREATE UNIQUE INDEX idx_users_age ON users (age);
-- Priority: HIGH | 100% unique values with no nulls - candidate for UNIQUE constraint
CREATE UNIQUE INDEX idx_users_salary ON users (salary);
-- Priority: HIGH | 100% unique values with no nulls - candidate for UNIQUE constraint
CREATE UNIQUE INDEX idx_users_created_at ON users (created_at);
-- Priority: HIGH | 100% unique values with no nulls - candidate for UNIQUE constraint
CREATE INDEX idx_users_created_at ON users (created_at);
-- Priority: HIGH | Date/time column - commonly used in range queries and sorting
CREATE INDEX idx_users_full_name ON users (full_name);
-- Priority: MEDIUM | Name/title column - commonly used for search
CREATE INDEX idx_users_status ON users (status);
-- Priority: MEDIUM | Status/category column with 3 values - good for filtered queries


-- Foreign Key Constraints (auto-detected)
-- NOTE: Uncomment after creating referenced tables
-- ALTER TABLE users ADD CONSTRAINT fk_users_customer_id
--     FOREIGN KEY (customer_id) REFERENCES customers(id);
-- Confidence: 90% | Column 'customer_id' matches FK pattern '(.+)_id$'
-- ALTER TABLE users ADD CONSTRAINT fk_users_order_id
--     FOREIGN KEY (order_id) REFERENCES orders(id);
-- Confidence: 90% | Column 'order_id' matches FK pattern '(.+)_id$'


-- Data Validation Rules (recommendations)
-- Column 'id' has no null values - add NOT NULL constraint
-- ALTER TABLE users ALTER COLUMN id SET NOT NULL;
-- Column 'id' is 100.0% unique - add UNIQUE constraint
-- ALTER TABLE users ADD CONSTRAINT uq_id UNIQUE (id);
-- Column 'customer_id' has no null values - add NOT NULL constraint
-- ALTER TABLE users ALTER COLUMN customer_id SET NOT NULL;
-- Column 'order_id' has no null values - add NOT NULL constraint
-- ALTER TABLE users ALTER COLUMN order_id SET NOT NULL;
-- Column 'order_id' is 100.0% unique - add UNIQUE constraint
-- ALTER TABLE users ADD CONSTRAINT uq_order_id UNIQUE (order_id);
-- Column 'email' has no null values - add NOT NULL constraint
-- ALTER TABLE users ALTER COLUMN email SET NOT NULL;
-- Column 'email' is 100.0% unique - add UNIQUE constraint
-- ALTER TABLE users ADD CONSTRAINT uq_email UNIQUE (email);
-- Maximum string length is 19 characters
-- -- Max observed length: 19. Consider VARCHAR(28)
-- Column 'full_name' has no null values - add NOT NULL constraint
-- ALTER TABLE users ALTER COLUMN full_name SET NOT NULL;
-- Column 'full_name' is 100.0% unique - add UNIQUE constraint
-- ALTER TABLE users ADD CONSTRAINT uq_full_name UNIQUE (full_name);
-- Maximum string length is 13 characters
-- -- Max observed length: 13. Consider VARCHAR(19)
-- Column 'age' has no null values - add NOT NULL constraint
-- ALTER TABLE users ALTER COLUMN age SET NOT NULL;
-- Column 'age' is 100.0% unique - add UNIQUE constraint
-- ALTER TABLE users ADD CONSTRAINT uq_age UNIQUE (age);
-- Column 'salary' has no null values - add NOT NULL constraint
-- ALTER TABLE users ALTER COLUMN salary SET NOT NULL;
-- Column 'salary' is 100.0% unique - add UNIQUE constraint
-- ALTER TABLE users ADD CONSTRAINT uq_salary UNIQUE (salary);
-- Column 'status' has no null values - add NOT NULL constraint
-- ALTER TABLE users ALTER COLUMN status SET NOT NULL;
-- Maximum string length is 8 characters
-- -- Max observed length: 8. Consider VARCHAR(12)
-- Column 'created_at' has no null values - add NOT NULL constraint
-- ALTER TABLE users ALTER COLUMN created_at SET NOT NULL;
-- Column 'created_at' is 100.0% unique - add UNIQUE constraint
-- ALTER TABLE users ADD CONSTRAINT uq_created_at UNIQUE (created_at);
-- Column 'is_verified' has no null values - add NOT NULL constraint
-- ALTER TABLE users ALTER COLUMN is_verified SET NOT NULL;

-- Insert Data (5 rows)
INSERT INTO users (id, customer_id, order_id, email, full_name, age, salary, status, created_at, is_verified) VALUES
    (1, 101, 1001, 'john@example.com', 'John Doe', 28, 75000.5, 'active', '2024-01-15 00:00:00', True),
    (2, 102, 1002, 'jane@example.com', 'Jane Smith', 34, 85000.0, 'active', '2024-02-20 00:00:00', True),
    (3, 101, 1003, 'bob@example.com', 'Bob O''Connor', 45, 95000.75, 'inactive', '2024-03-10 00:00:00', False),
    (4, 103, 1004, 'alice@example.com', 'Alice Johnson', 29, 72000.0, 'pending', '2024-04-05 00:00:00', True),
    (5, 102, 1005, 'charlie@example.com', 'Charlie Brown', 52, 105000.25, 'active', '2024-05-12 00:00:00', True);



-- Script generation complete
-- Total INSERT statements: 1